name: voice-hub

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_ADDR: ":8080"
      WEB_DIR: "/app/web"
      APP_HOSTNAME: "localhost"
      PUBLIC_IP: "127.0.0.1"
      APP_ADMIN_PASSWORD: "dev"
      APP_COOKIE_SECURE: "false"
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
      - "3478:3478/udp"
      - "10000-10100:10000-10100/udp"
      - "49160-49200:49160-49200/udp"
