name: voice-hub

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_ADDR: ":8080"
      WEB_DIR: "/app/web"
      STUN_URL: "stun:localhost:3478"
      TURN_URL: "turn:localhost:3478?transport=udp"
      TURN_USERNAME: "room"
      TURN_PASSWORD: "room-secret"
      APP_AUTH_USER: "dev"
      APP_AUTH_PASSWORD: "dev"
      APP_SESSION_SECRET: "dev-session-secret-32-bytes-long!"
      APP_COOKIE_SECURE: "false"
    ports:
      - "8080:8080"
      - "10000-10100:10000-10100/udp"

  coturn:
    image: coturn/coturn:4.10-alpine
    command:
      - --log-file=stdout
      - --no-cli
      - --no-tls
      - --no-dtls
      - --fingerprint
      - --realm=localhost
      - --user=room:room-secret
      - --listening-port=3478
      - --min-port=49160
      - --max-port=49200
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49160-49200:49160-49200/udp"
