name: voice-hub

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_ADDR: ":8080"
      WEB_DIR: "/app/web"
      APP_HOSTNAME: "localhost"
      PUBLIC_IP: "127.0.0.1"
      TURN_SHARED_SECRET: "dev-turn-shared-secret-change-me"
      APP_AUTH_USER: "dev"
      APP_AUTH_PASSWORD: "dev"
      APP_SESSION_SECRET: "dev-session-secret-32-bytes-long!"
      APP_COOKIE_SECURE: "false"
    ports:
      - "8080:8080"
      - "3478:3478/udp"
      - "10000-10100:10000-10100/udp"
      - "49160-49200:49160-49200/udp"
